[libdefaults]
    default_realm = IPP-GARCHING.MPG.DE
	clockskew = 300
	ticket_lifetime = 2592000
    renew_lifetime = 7d
	v4_instance_resolve = false
	forwardable = true
	forward = true
	proxiable = true

[realms]
	IPP-GARCHING.MPG.DE = {
        kdc = kerberos1.rzg.mpg.de
        kdc = kerberos2.rzg.mpg.de
        kdc = kerberos3.rzg.mpg.de
        admin_server = kerberos1.rzg.mpg.de
	}

[domain_realm]
    mpcdf.mpg.de = IPP-GARCHING.MPG.DE
    .mpcdf.mpg.de = IPP-GARCHING.MPG.DE
    rzg.mpg.de = IPP-GARCHING.MPG.DE
    .rzg.mpg.de = IPP-GARCHING.MPG.DE
    ipp.mpg.de = IPP-GARCHING.MPG.DE
    .ipp.mpg.de = IPP-GARCHING.MPG.DE
    ipp-hgw.mpg.de = IPP-GARCHING.MPG.DE
    .ipp-hgw.mpg.de = IPP-GARCHING.MPG.DE
    ipp-garching.mpg.de = IPP-GARCHING.MPG.DE
    .ipp-garching.mpg.de = IPP-GARCHING.MPG.DE